name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      DOCKER_IMAGE_TAG: "conrad302/hello-web-app:2.1"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker
      run: echo ${{ secrets.DOCKER_CLI_ACCESS_TOKEN }} | docker login --username conrad302 --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_TAG }}
    - name: Push image to Docker Hub
      run: docker push ${{ env.DOCKER_IMAGE_TAG }}
